cc_test(
    name = "core_test",
    size = "small",
    srcs = ["core_test.cc"],
    deps = [
        "//libs/core:tensor",
        "@googletest//:gtest",
        "@googletest//:gtest_main",
    ],
)
